#!/usr/bin/env bash
# installs nginx web server

# Update package lists
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Configure Nginx to listen on port 80 and return "Hello World!" at the root
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'

# Restart Nginx
sudo service nginx restart

