#!/usr/bin/env bash
# installs nginx on web 01

sudo apt-get update
sudo apt-get install nginx
sudo ufw allow 'Nginx HTTP'

echo 'Hello World'!| sudo tee /var/www/html/index.html

#testing nginx config
sudo nginx -t

sudo service nginx start
