#!/usr/bin/env bash
#Bash script fixes the issue with nginx server not listening on port 80
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
