#!/usr/bin/env bash
# This script Displays FizzBuzz when the number is a multiple of 3 and 5
i=1
while [ "$i" -le 100 ]
do
    if [ $((i % 15)) -eq 0 ]
    then
        echo "FizzBuzz"
    elif [ $((i % 5)) -eq 0 ]
    then
        echo "Buzz"
    elif [ $((i % 3)) -eq 0 ]
    then
        echo "Fizz"
    else
        echo "$i"
    fi
    i=$((i + 1))
done
i=$i
