#!/usr/bin/env bash
# Shell script to reconfigures the localhost addresses and subnet mask in
# the copy of the host file
# changes localhost from 127.0.0.1 to 127.0.0.2
# changes subnet mask alias 8.8.8.8 to route to facebook.com
cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
