#!/usr/bin/env bash
# Shell script that displays all the active IPv4 IP addresses on the current machine where it is currently executing
ifconfig | grep -Eo "inet (addr:)?([\d]*\.){3}[\d]*" | cut -b 6-
