#!/usr/bin/env bash
# Generate RSA key pair
openssl genrsa -aes256 -passout pass:betty -out school.key 4096

# Extract the public key from the private key
openssl rsa -in school.key -passin pass:betty -pubout -out school.pub

echo "RSA key pair generated successfully."
